// Generated from XML currency pairs provided by the user
export const AVAILABLE_QUOTES = [
  { name: "Dólar Americano/Real Brasileiro", code: "USD-BRL" },
  { name: "Dólar Americano/Real Brasileiro Turismo", code: "USD-BRLT" },
  { name: "Dólar Canadense/Real Brasileiro", code: "CAD-BRL" },
  { name: "Euro/Real Brasileiro", code: "EUR-BRL" },
  { name: "Libra Esterlina/Real Brasileiro", code: "GBP-BRL" },
  { name: "Peso Argentino/Real Brasileiro", code: "ARS-BRL" },
  { name: "Bitcoin/Real Brasileiro", code: "BTC-BRL" },
  { name: "Litecoin/Real Brasileiro", code: "LTC-BRL" },
  { name: "Iene Japonês/Real Brasileiro", code: "JPY-BRL" },
  { name: "Franco Suíço/Real Brasileiro", code: "CHF-BRL" },
  { name: "Dólar Australiano/Real Brasileiro", code: "AUD-BRL" },
  { name: "Yuan Chinês/Real Brasileiro", code: "CNY-BRL" },
  { name: "Novo Shekel Israelense/Real Brasileiro", code: "ILS-BRL" },
  { name: "Ethereum/Real Brasileiro", code: "ETH-BRL" },
  { name: "XRP/Real Brasileiro", code: "XRP-BRL" },
  { name: "Euro/Dólar Americano", code: "EUR-USD" },
  { name: "Dólar Canadense/Dólar Americano", code: "CAD-USD" },
  { name: "Libra Esterlina/Dólar Americano", code: "GBP-USD" },
  { name: "Peso Argentino/Dólar Americano", code: "ARS-USD" },
  { name: "Iene Japonês/Dólar Americano", code: "JPY-USD" },
  { name: "Franco Suíço/Dólar Americano", code: "CHF-USD" },
  { name: "Dólar Australiano/Dólar Americano", code: "AUD-USD" },
  { name: "Yuan Chinês/Dólar Americano", code: "CNY-USD" },
  { name: "Novo Shekel Israelense/Dólar Americano", code: "ILS-USD" },
  { name: "Bitcoin/Dólar Americano", code: "BTC-USD" },
  { name: "Litecoin/Dólar Americano", code: "LTC-USD" },
  { name: "Ethereum/Dólar Americano", code: "ETH-USD" },
  { name: "XRP/Dólar Americano", code: "XRP-USD" },
  { name: "Real Brasileiro/Dólar Americano", code: "BRL-USD" },
  { name: "Real Brasileiro/Euro", code: "BRL-EUR" },
  { name: "Dólar Americano/Euro", code: "USD-EUR" },
  { name: "Dólar Canadense/Euro", code: "CAD-EUR" },
  { name: "Libra Esterlina/Euro", code: "GBP-EUR" },
  { name: "Peso Argentino/Euro", code: "ARS-EUR" },
  { name: "Iene Japonês/Euro", code: "JPY-EUR" },
  { name: "Franco Suíço/Euro", code: "CHF-EUR" },
  { name: "Dólar Australiano/Euro", code: "AUD-EUR" },
  { name: "Yuan Chinês/Euro", code: "CNY-EUR" },
  { name: "Novo Shekel Israelense/Euro", code: "ILS-EUR" },
  { name: "Bitcoin/Euro", code: "BTC-EUR" },
  { name: "Litecoin/Euro", code: "LTC-EUR" },
  { name: "Ethereum/Euro", code: "ETH-EUR" },
  { name: "XRP/Euro", code: "XRP-EUR" },
  { name: "Dogecoin/Real Brasileiro", code: "DOGE-BRL" },
  { name: "Dogecoin/Euro", code: "DOGE-EUR" },
  { name: "Dogecoin/Dólar Americano", code: "DOGE-USD" },
  { name: "Dólar Americano/Iene Japonês", code: "USD-JPY" },
  { name: "Dólar Americano/Franco Suíço", code: "USD-CHF" },
  { name: "Dólar Americano/Dólar Canadense", code: "USD-CAD" },
  { name: "Dólar Neozelandês/Dólar Americano", code: "NZD-USD" },
  { name: "Dólar Americano/Rand Sul-Africano", code: "USD-ZAR" },
  { name: "Dólar Americano/Nova Lira Turca", code: "USD-TRY" },
  { name: "Dólar Americano/Peso Mexicano", code: "USD-MXN" },
  { name: "Dólar Americano/Zlóti Polonês", code: "USD-PLN" },
  { name: "Dólar Americano/Coroa Sueca", code: "USD-SEK" },
  { name: "Dólar Americano/Dólar de Cingapura", code: "USD-SGD" },
  { name: "Dólar Americano/Coroa Dinamarquesa", code: "USD-DKK" },
  { name: "Dólar Americano/Coroa Norueguesa", code: "USD-NOK" },
  { name: "Dólar Americano/Novo Shekel Israelense", code: "USD-ILS" },
  { name: "Dólar Americano/Florim Húngaro", code: "USD-HUF" },
  { name: "Dólar Americano/Coroa Checa", code: "USD-CZK" },
  { name: "Dólar Americano/Baht Tailandês", code: "USD-THB" },
  { name: "Dólar Americano/Dirham dos Emirados", code: "USD-AED" },
  { name: "Dólar Americano/Dinar Jordaniano", code: "USD-JOD" },
  { name: "Dólar Americano/Dinar Kuwaitiano", code: "USD-KWD" },
  { name: "Dólar Americano/Dólar de Hong Kong", code: "USD-HKD" },
  { name: "Dólar Americano/Riyal Saudita", code: "USD-SAR" },
  { name: "Dólar Americano/Rúpia Indiana", code: "USD-INR" },
  { name: "Dólar Americano/Won Sul-Coreano", code: "USD-KRW" },
  { name: "Dólar de Fiji/Dólar Americano", code: "FJD-USD" },
  { name: "Cedi Ganês/Dólar Americano", code: "GHS-USD" },
  { name: "Dólar das Ilhas Cayman/Dólar Americano", code: "KYD-USD" },
  { name: "Dólar de Cingapura/Dólar Americano", code: "SGD-USD" },
  { name: "Dólar Americano/Lek Albanês", code: "USD-ALL" },
  { name: "Dólar Americano/Dram Armênio", code: "USD-AMD" },
  { name: "Dólar Americano/Guilder das Antilhas", code: "USD-ANG" },
  { name: "Dólar Americano/Peso Argentino", code: "USD-ARS" },
  { name: "Dólar Americano/Dólar Australiano", code: "USD-AUD" },
  { name: "Dólar Americano/Dólar de Barbados", code: "USD-BBD" },
  { name: "Dólar Americano/Taka de Bangladesh", code: "USD-BDT" },
  { name: "Dólar Americano/Lev Búlgaro", code: "USD-BGN" },
  { name: "Dólar Americano/Dinar do Bahrein", code: "USD-BHD" },
  { name: "Dólar Americano/Franco Burundinense", code: "USD-BIF" },
  { name: "Dólar Americano/Dólar de Brunei", code: "USD-BND" },
  { name: "Dólar Americano/Boliviano", code: "USD-BOB" },
  { name: "Dólar Americano/Dólar das Bahamas", code: "USD-BSD" },
  { name: "Dólar Americano/Pula de Botswana", code: "USD-BWP" },
  { name: "Dólar Americano/Dólar de Belize", code: "USD-BZD" },
  { name: "Dólar Americano/Peso Chileno", code: "USD-CLP" },
  { name: "Dólar Americano/Yuan Chinês", code: "USD-CNY" },
  { name: "Dólar Americano/Peso Colombiano", code: "USD-COP" },
  { name: "Dólar Americano/Colón Costarriquenho", code: "USD-CRC" },
  { name: "Dólar Americano/Peso Cubano", code: "USD-CUP" },
  { name: "Dólar Americano/Franco do Djubouti", code: "USD-DJF" },
  { name: "Dólar Americano/Peso Dominicano", code: "USD-DOP" },
  { name: "Dólar Americano/Dinar Argelino", code: "USD-DZD" },
  { name: "Dólar Americano/Libra Egípcia", code: "USD-EGP" },
  { name: "Dólar Americano/Birr Etíope", code: "USD-ETB" },
  { name: "Dólar Americano/Dólar de Fiji", code: "USD-FJD" },
  { name: "Dólar Americano/Libra Esterlina", code: "USD-GBP" },
  { name: "Dólar Americano/Lari Georgiano", code: "USD-GEL" },
  { name: "Dólar Americano/Cedi Ganês", code: "USD-GHS" },
  { name: "Dólar Americano/Dalasi da Gâmbia", code: "USD-GMD" },
  { name: "Dólar Americano/Franco de Guiné", code: "USD-GNF" },
  { name: "Dólar Americano/Quetzal Guatemalteco", code: "USD-GTQ" },
  { name: "Dólar Americano/Lempira Hondurenha", code: "USD-HNL" },
  { name: "Dólar Americano/Kuna Croata", code: "USD-HRK" },
  { name: "Dólar Americano/Gourde Haitiano", code: "USD-HTG" },
  { name: "Dólar Americano/Rupia Indonésia", code: "USD-IDR" },
  { name: "Dólar Americano/Dinar Iraquiano", code: "USD-IQD" },
  { name: "Dólar Americano/Rial Iraniano", code: "USD-IRR" },
  { name: "Dólar Americano/Coroa Islandesa", code: "USD-ISK" },
  { name: "Dólar Americano/Dólar Jamaicano", code: "USD-JMD" },
  { name: "Dólar Americano/Shilling Queniano", code: "USD-KES" },
  { name: "Dólar Americano/Riel Cambojano", code: "USD-KHR" },
  { name: "Dólar Americano/Franco Comorense", code: "USD-KMF" },
  { name: "Dólar Americano/Tengue Cazaquistanês", code: "USD-KZT" },
  { name: "Dólar Americano/Kip Laosiano", code: "USD-LAK" },
  { name: "Dólar Americano/Libra Libanesa", code: "USD-LBP" },
  { name: "Dólar Americano/Rúpia de Sri Lanka", code: "USD-LKR" },
  { name: "Dólar Americano/Loti do Lesoto", code: "USD-LSL" },
  { name: "Dólar Americano/Dinar Líbio", code: "USD-LYD" },
  { name: "Dólar Americano/Dirham Marroquino", code: "USD-MAD" },
  { name: "Dólar Americano/Leu Moldavo", code: "USD-MDL" },
  { name: "Dólar Americano/Ariary Madagascarense", code: "USD-MGA" },
  { name: "Dólar Americano/Denar Macedônio", code: "USD-MKD" },
  { name: "Dólar Americano/Kyat de Mianmar", code: "USD-MMK" },
  { name: "Dólar Americano/Pataca de Macau", code: "USD-MOP" },
  { name: "Dólar Americano/Ouguiya Mauritana", code: "USD-MRO" },
  { name: "Dólar Americano/Rúpia Mauriciana", code: "USD-MUR" },
  { name: "Dólar Americano/Rufiyaa Maldiva", code: "USD-MVR" },
  { name: "Dólar Americano/Kwacha Malauiana", code: "USD-MWK" },
  { name: "Dólar Americano/Ringgit Malaio", code: "USD-MYR" },
  { name: "Dólar Americano/Dólar Namíbio", code: "USD-NAD" },
  { name: "Dólar Americano/Naira Nigeriana", code: "USD-NGN" },
  { name: "Dólar Americano/Córdoba Nicaragueense", code: "USD-NIO" },
  { name: "Dólar Americano/Rúpia Nepalesa", code: "USD-NPR" },
  { name: "Dólar Americano/Dólar Neozelandês", code: "USD-NZD" },
  { name: "Dólar Americano/Rial Omanense", code: "USD-OMR" },
  { name: "Dólar Americano/Balboa Panamenho", code: "USD-PAB" },
  { name: "Dólar Americano/Sol do Peru", code: "USD-PEN" },
  { name: "Dólar Americano/Kina Papua-Nova Guiné", code: "USD-PGK" },
  { name: "Dólar Americano/Peso Filipino", code: "USD-PHP" },
  { name: "Dólar Americano/Rúpia Paquistanesa", code: "USD-PKR" },
  { name: "Dólar Americano/Guarani Paraguaio", code: "USD-PYG" },
  { name: "Dólar Americano/Rial Catarense", code: "USD-QAR" },
  { name: "Dólar Americano/Leu Romeno", code: "USD-RON" },
  { name: "Dólar Americano/Dinar Sérvio", code: "USD-RSD" },
  { name: "Dólar Americano/Franco Ruandês", code: "USD-RWF" },
  { name: "Dólar Americano/Rúpias de Seicheles", code: "USD-SCR" },
  { name: "Dólar Americano/Libra Sudanesa", code: "USD-SDG" },
  { name: "Dólar Americano/Shilling Somaliano", code: "USD-SOS" },
  { name: "Dólar Americano/Dobra São Tomé/Príncipe", code: "USD-STD" },
  { name: "Dólar Americano/Colon de El Salvador", code: "USD-SVC" },
  { name: "Dólar Americano/Libra Síria", code: "USD-SYP" },
  { name: "Dólar Americano/Lilangeni Suazilandês", code: "USD-SZL" },
  { name: "Dólar Americano/Dinar Tunisiano", code: "USD-TND" },
  { name: "Dólar Americano/Dólar de Trinidad", code: "USD-TTD" },
  { name: "Dólar Americano/Dólar Taiuanês", code: "USD-TWD" },
  { name: "Dólar Americano/Shilling Tanzaniano", code: "USD-TZS" },
  { name: "Dólar Americano/Hryvinia Ucraniana", code: "USD-UAH" },
  { name: "Dólar Americano/Shilling Ugandês", code: "USD-UGX" },
  { name: "Dólar Americano/Peso Uruguaio", code: "USD-UYU" },
  { name: "Dólar Americano/Som Uzbequistanês", code: "USD-UZS" },
  { name: "Dólar Americano/Bolívar Venezuelano", code: "USD-VEF" },
  { name: "Dólar Americano/Dong Vietnamita", code: "USD-VND" },
  { name: "Dólar Americano/Vatu de Vanuatu", code: "USD-VUV" },
  { name: "Dólar Americano/Franco CFA Central", code: "USD-XAF" },
  { name: "Dólar Americano/Dólar do Caribe Oriental", code: "USD-XCD" },
  { name: "Dólar Americano/Franco CFA Ocidental", code: "USD-XOF" },
  { name: "Dólar Americano/Franco CFP", code: "USD-XPF" },
  { name: "Dólar Americano/Riyal Iemenita", code: "USD-YER" },
  { name: "Dólar Americano/Kwacha Zambiana", code: "USD-ZMK" },
  { name: "Dirham dos Emirados/Dólar Americano", code: "AED-USD" },
  { name: "Coroa Dinamarquesa/Dólar Americano", code: "DKK-USD" },
  { name: "Dólar de Hong Kong/Dólar Americano", code: "HKD-USD" },
  { name: "Peso Mexicano/Dólar Americano", code: "MXN-USD" },
  { name: "Coroa Norueguesa/Dólar Americano", code: "NOK-USD" },
  { name: "Zlóti Polonês/Dólar Americano", code: "PLN-USD" },
  { name: "Rublo Russo/Dólar Americano", code: "RUB-USD" },
  { name: "Riyal Saudita/Dólar Americano", code: "SAR-USD" },
  { name: "Coroa Sueca/Dólar Americano", code: "SEK-USD" },
  { name: "Nova Lira Turca/Dólar Americano", code: "TRY-USD" },
  { name: "Dólar Taiuanês/Dólar Americano", code: "TWD-USD" },
  { name: "Bolívar Venezuelano/Dólar Americano", code: "VEF-USD" },
  { name: "Rand Sul-Africano/Dólar Americano", code: "ZAR-USD" },
  { name: "Peso Uruguaio/Dólar Americano", code: "UYU-USD" },
  { name: "Guarani Paraguaio/Dólar Americano", code: "PYG-USD" },
  { name: "Peso Chileno/Dólar Americano", code: "CLP-USD" },
  { name: "Peso Colombiano/Dólar Americano", code: "COP-USD" },
  { name: "Sol do Peru/Dólar Americano", code: "PEN-USD" },
  { name: "Córdoba Nicaraguense/Dólar Americano", code: "NIO-USD" },
  { name: "Boliviano/Dólar Americano", code: "BOB-USD" },
  { name: "Won Sul-Coreano/Dólar Americano", code: "KRW-USD" },
  { name: "Libra Egípcia/Dólar Americano", code: "EGP-USD" },
  { name: "Dólar Americano/Rublo Bielorrusso", code: "USD-BYN" },
  { name: "Dólar Americano/Metical de Moçambique", code: "USD-MZN" },
  { name: "Rúpia Indiana/Dólar Americano", code: "INR-USD" },
  { name: "Dinar Jordaniano/Dólar Americano", code: "JOD-USD" },
  { name: "Dinar Kuwaitiano/Dólar Americano", code: "KWD-USD" },
  { name: "Dólar Americano/Manat Azeri", code: "USD-AZN" },
  { name: "Dólar Americano/Yuan chinês offshore", code: "USD-CNH" },
  { name: "Dólar Americano/Som Quirguistanês", code: "USD-KGS" },
  { name: "Dólar Americano/Somoni do Tajiquistão", code: "USD-TJS" },
  { name: "Dólar Americano/Rublo Russo", code: "USD-RUB" },
  { name: "Ringgit Malaio/Dólar Americano", code: "MYR-USD" },
  { name: "Hryvinia Ucraniana/Dólar Americano", code: "UAH-USD" },
  { name: "Florim Húngaro/Dólar Americano", code: "HUF-USD" },
  { name: "Rupia Indonésia/Dólar Americano", code: "IDR-USD" },
  { name: "Dólar Americano/Kwanza Angolano", code: "USD-AOA" },
  { name: "Dong Vietnamita/Dólar Americano", code: "VND-USD" },
  { name: "Rublo Bielorrusso/Dólar Americano", code: "BYN-USD" },
  { name: "Brent Spot/Dólar Americano", code: "XBR-USD" },
  { name: "Baht Tailandês/Dólar Americano", code: "THB-USD" },
  { name: "Peso Filipino/Dólar Americano", code: "PHP-USD" },
  { name: "Dólar Americano/TMT", code: "USD-TMT" },
  { name: "Prata/Dólar Americano", code: "XAGG-USD" },
  { name: "Dólar Americano/Mongolian Tugrik", code: "USD-MNT" },
  { name: "Dólar Americano/Afghani do Afeganistão", code: "USD-AFN" },
  { name: "Afghani do Afeganistão/Dólar Americano", code: "AFN-USD" },
  { name: "Libra Síria/Dólar Americano", code: "SYP-USD" },
  { name: "Rial Iraniano/Dólar Americano", code: "IRR-USD" },
  { name: "Dinar Iraquiano/Dólar Americano", code: "IQD-USD" },
  { name: "Dólar Americano/Naira Nigeriana", code: "USD-NGNI" },
  { name: "Dólar Americano/Dólar Zimbabuense", code: "USD-ZWL" },
  { name: "Real Brasileiro/Peso Argentino", code: "BRL-ARS" },
  { name: "Real Brasileiro/Dólar Australiano", code: "BRL-AUD" },
  { name: "Real Brasileiro/Dólar Canadense", code: "BRL-CAD" },
  { name: "Real Brasileiro/Franco Suíço", code: "BRL-CHF" },
  { name: "Real Brasileiro/Peso Chileno", code: "BRL-CLP" },
  { name: "Real Brasileiro/Coroa Dinamarquesa", code: "BRL-DKK" },
  { name: "Real Brasileiro/Dólar de Hong Kong", code: "BRL-HKD" },
  { name: "Real Brasileiro/Iene Japonês", code: "BRL-JPY" },
  { name: "Real Brasileiro/Peso Mexicano", code: "BRL-MXN" },
  { name: "Real Brasileiro/Dólar de Cingapura", code: "BRL-SGD" },
  { name: "Dólar de Cingapura/Real Brasileiro", code: "SGD-BRL" },
  { name: "Dirham dos Emirados/Real Brasileiro", code: "AED-BRL" },
  { name: "Real Brasileiro/Dirham dos Emirados", code: "BRL-AED" },
  { name: "Real Brasileiro/Dólar de Barbados", code: "BRL-BBD" },
  { name: "Real Brasileiro/Dinar do Bahrein", code: "BRL-BHD" },
  { name: "Real Brasileiro/Yuan Chinês", code: "BRL-CNY" },
  { name: "Real Brasileiro/Coroa Checa", code: "BRL-CZK" },
  { name: "Real Brasileiro/Libra Egípcia", code: "BRL-EGP" },
  { name: "Real Brasileiro/Libra Esterlina", code: "BRL-GBP" },
  { name: "Real Brasileiro/Florim Húngaro", code: "BRL-HUF" },
  { name: "Real Brasileiro/Rupia Indonésia", code: "BRL-IDR" },
  { name: "Real Brasileiro/Novo Shekel Israelense", code: "BRL-ILS" },
  { name: "Real Brasileiro/Rúpia Indiana", code: "BRL-INR" },
  { name: "Real Brasileiro/Coroa Islandesa", code: "BRL-ISK" },
  { name: "Real Brasileiro/Dólar Jamaicano", code: "BRL-JMD" },
  { name: "Real Brasileiro/Dinar Jordaniano", code: "BRL-JOD" },
  { name: "Real Brasileiro/Shilling Queniano", code: "BRL-KES" },
  { name: "Real Brasileiro/Won Sul-Coreano", code: "BRL-KRW" },
  { name: "Real Brasileiro/Libra Libanesa", code: "BRL-LBP" },
  { name: "Real Brasileiro/Rúpia de Sri Lanka", code: "BRL-LKR" },
  { name: "Real Brasileiro/Dirham Marroquino", code: "BRL-MAD" },
  { name: "Real Brasileiro/Ringgit Malaio", code: "BRL-MYR" },
  { name: "Real Brasileiro/Dólar Namíbio", code: "BRL-NAD" },
  { name: "Real Brasileiro/Coroa Norueguesa", code: "BRL-NOK" },
  { name: "Real Brasileiro/Rúpia Nepalesa", code: "BRL-NPR" },
  { name: "Real Brasileiro/Dólar Neozelandês", code: "BRL-NZD" },
  { name: "Real Brasileiro/Rial Omanense", code: "BRL-OMR" },
  { name: "Real Brasileiro/Balboa Panamenho", code: "BRL-PAB" },
  { name: "Real Brasileiro/Peso Filipino", code: "BRL-PHP" },
  { name: "Real Brasileiro/Rúpia Paquistanesa", code: "BRL-PKR" },
  { name: "Real Brasileiro/Zlóti Polonês", code: "BRL-PLN" },
  { name: "Real Brasileiro/Rial Catarense", code: "BRL-QAR" },
  { name: "Real Brasileiro/Leu Romeno", code: "BRL-RON" },
  { name: "Real Brasileiro/Rublo Russo", code: "BRL-RUB" },
  { name: "Real Brasileiro/Riyal Saudita", code: "BRL-SAR" },
  { name: "Real Brasileiro/Coroa Sueca", code: "BRL-SEK" },
  { name: "Real Brasileiro/Baht Tailandês", code: "BRL-THB" },
  { name: "Real Brasileiro/Nova Lira Turca", code: "BRL-TRY" },
  { name: "Real Brasileiro/Bolívar Venezuelano", code: "BRL-VEF" },
  { name: "Real Brasileiro/Franco CFA Central", code: "BRL-XAF" },
  { name: "Real Brasileiro/Dólar do Caribe Oriental", code: "BRL-XCD" },
  { name: "Real Brasileiro/Franco CFA Ocidental", code: "BRL-XOF" },
  { name: "Real Brasileiro/Rand Sul-Africano", code: "BRL-ZAR" },
  { name: "Real Brasileiro/Dólar Taiuanês", code: "BRL-TWD" },
  { name: "Coroa Dinamarquesa/Real Brasileiro", code: "DKK-BRL" },
  { name: "Dólar de Hong Kong/Real Brasileiro", code: "HKD-BRL" },
  { name: "Peso Mexicano/Real Brasileiro", code: "MXN-BRL" },
  { name: "Coroa Norueguesa/Real Brasileiro", code: "NOK-BRL" },
  { name: "Dólar Neozelandês/Real Brasileiro", code: "NZD-BRL" },
  { name: "Zlóti Polonês/Real Brasileiro", code: "PLN-BRL" },
  { name: "Riyal Saudita/Real Brasileiro", code: "SAR-BRL" },
  { name: "Coroa Sueca/Real Brasileiro", code: "SEK-BRL" },
  { name: "Baht Tailandês/Real Brasileiro", code: "THB-BRL" },
  { name: "Nova Lira Turca/Real Brasileiro", code: "TRY-BRL" },
  { name: "Dólar Taiuanês/Real Brasileiro", code: "TWD-BRL" },
  { name: "Bolívar Venezuelano/Real Brasileiro", code: "VEF-BRL" },
  { name: "Rand Sul-Africano/Real Brasileiro", code: "ZAR-BRL" },
  { name: "Real Brasileiro/Guarani Paraguaio", code: "BRL-PYG" },
  { name: "Real Brasileiro/Peso Uruguaio", code: "BRL-UYU" },
  { name: "Real Brasileiro/Peso Colombiano", code: "BRL-COP" },
  { name: "Real Brasileiro/Sol do Peru", code: "BRL-PEN" },
  { name: "Real Brasileiro/Boliviano", code: "BRL-BOB" },
  { name: "Peso Chileno/Real Brasileiro", code: "CLP-BRL" },
  { name: "Guarani Paraguaio/Real Brasileiro", code: "PYG-BRL" },
  { name: "Peso Uruguaio/Real Brasileiro", code: "UYU-BRL" },
  { name: "Peso Colombiano/Real Brasileiro", code: "COP-BRL" },
  { name: "Sol do Peru/Real Brasileiro", code: "PEN-BRL" },
  { name: "Boliviano/Real Brasileiro", code: "BOB-BRL" },
  { name: "Rublo Russo/Real Brasileiro", code: "RUB-BRL" },
  { name: "Rúpia Indiana/Real Brasileiro", code: "INR-BRL" },
  { name: "Euro/Libra Esterlina", code: "EUR-GBP" },
  { name: "Euro/Iene Japonês", code: "EUR-JPY" },
  { name: "Euro/Franco Suíço", code: "EUR-CHF" },
  { name: "Euro/Dólar Australiano", code: "EUR-AUD" },
  { name: "Euro/Dólar Canadense", code: "EUR-CAD" },
  { name: "Euro/Coroa Norueguesa", code: "EUR-NOK" },
  { name: "Euro/Coroa Dinamarquesa", code: "EUR-DKK" },
  { name: "Euro/Zlóti Polonês", code: "EUR-PLN" },
  { name: "Euro/Dólar Neozelandês", code: "EUR-NZD" },
  { name: "Euro/Coroa Sueca", code: "EUR-SEK" },
  { name: "Euro/Novo Shekel Israelense", code: "EUR-ILS" },
  { name: "Euro/Nova Lira Turca", code: "EUR-TRY" },
  { name: "Euro/Baht Tailandês", code: "EUR-THB" },
  { name: "Euro/Rand Sul-Africano", code: "EUR-ZAR" },
  { name: "Euro/Peso Mexicano", code: "EUR-MXN" },
  { name: "Euro/Dólar de Cingapura", code: "EUR-SGD" },
  { name: "Euro/Florim Húngaro", code: "EUR-HUF" },
  { name: "Euro/Dólar de Hong Kong", code: "EUR-HKD" },
  { name: "Euro/Coroa Checa", code: "EUR-CZK" },
  { name: "Euro/Won Sul-Coreano", code: "EUR-KRW" },
  { name: "Dinar do Bahrein/Euro", code: "BHD-EUR" },
  { name: "Euro/Dirham dos Emirados", code: "EUR-AED" },
  { name: "Euro/Afghani do Afeganistão", code: "EUR-AFN" },
  { name: "Euro/Lek Albanês", code: "EUR-ALL" },
  { name: "Euro/Guilder das Antilhas", code: "EUR-ANG" },
  { name: "Euro/Peso Argentino", code: "EUR-ARS" },
  { name: "Euro/Marco Conversível", code: "EUR-BAM" },
  { name: "Euro/Dólar de Barbados", code: "EUR-BBD" },
  { name: "Euro/Taka de Bangladesh", code: "EUR-BDT" },
  { name: "Euro/Lev Búlgaro", code: "EUR-BGN" },
  { name: "Euro/Dinar do Bahrein", code: "EUR-BHD" },
  { name: "Euro/Franco Burundinense", code: "EUR-BIF" },
  { name: "Euro/Dólar de Brunei", code: "EUR-BND" },
  { name: "Euro/Boliviano", code: "EUR-BOB" },
  { name: "Euro/Dólar das Bahamas", code: "EUR-BSD" },
  { name: "Euro/Pula de Botswana", code: "EUR-BWP" },
  { name: "Euro/Rublo Bielorrusso", code: "EUR-BYN" },
  { name: "Euro/Dólar de Belize", code: "EUR-BZD" },
  { name: "Euro/Peso Chileno", code: "EUR-CLP" },
  { name: "Euro/Yuan Chinês", code: "EUR-CNY" },
  { name: "Euro/Peso Colombiano", code: "EUR-COP" },
  { name: "Euro/Colón Costarriquenho", code: "EUR-CRC" },
  { name: "Euro/Peso Cubano", code: "EUR-CUP" },
  { name: "Euro/Escudo cabo-verdiano", code: "EUR-CVE" },
  { name: "Euro/Franco do Djubouti", code: "EUR-DJF" },
  { name: "Euro/Peso Dominicano", code: "EUR-DOP" },
  { name: "Euro/Dinar Argelino", code: "EUR-DZD" },
  { name: "Euro/Libra Egípcia", code: "EUR-EGP" },
  { name: "Euro/Birr Etíope", code: "EUR-ETB" },
  { name: "Euro/Dólar de Fiji", code: "EUR-FJD" },
  { name: "Euro/Cedi Ganês", code: "EUR-GHS" },
  { name: "Euro/Dalasi da Gâmbia", code: "EUR-GMD" },
  { name: "Euro/Franco de Guiné", code: "EUR-GNF" },
  { name: "Euro/Quetzal Guatemalteco", code: "EUR-GTQ" },
  { name: "Euro/Lempira Hondurenha", code: "EUR-HNL" },
  { name: "Euro/Kuna Croata", code: "EUR-HRK" },
  { name: "Euro/Gourde Haitiano", code: "EUR-HTG" },
  { name: "Euro/Rupia Indonésia", code: "EUR-IDR" },
  { name: "Euro/Rúpia Indiana", code: "EUR-INR" },
  { name: "Euro/Dinar Iraquiano", code: "EUR-IQD" },
  { name: "Euro/Rial Iraniano", code: "EUR-IRR" },
  { name: "Euro/Coroa Islandesa", code: "EUR-ISK" },
  { name: "Euro/Dólar Jamaicano", code: "EUR-JMD" },
  { name: "Euro/Dinar Jordaniano", code: "EUR-JOD" },
  { name: "Euro/Shilling Queniano", code: "EUR-KES" },
  { name: "Euro/Riel Cambojano", code: "EUR-KHR" },
  { name: "Euro/Dinar Kuwaitiano", code: "EUR-KWD" },
  { name: "Euro/Dólar das Ilhas Cayman", code: "EUR-KYD" },
  { name: "Euro/Tengue Cazaquistanês", code: "EUR-KZT" },
  { name: "Euro/Kip Laosiano", code: "EUR-LAK" },
  { name: "Euro/Libra Libanesa", code: "EUR-LBP" },
  { name: "Euro/Rúpia de Sri Lanka", code: "EUR-LKR" },
  { name: "Euro/Loti do Lesoto", code: "EUR-LSL" },
  { name: "Euro/Dinar Líbio", code: "EUR-LYD" },
  { name: "Euro/Dirham Marroquino", code: "EUR-MAD" },
  { name: "Euro/Leu Moldavo", code: "EUR-MDL" },
  { name: "Euro/Ariary Madagascarense", code: "EUR-MGA" },
  { name: "Euro/Denar Macedônio", code: "EUR-MKD" },
  { name: "Euro/Kyat de Mianmar", code: "EUR-MMK" },
  { name: "Euro/Pataca de Macau", code: "EUR-MOP" },
  { name: "Euro/Ouguiya Mauritana", code: "EUR-MRO" },
  { name: "Euro/Rúpia Mauriciana", code: "EUR-MUR" },
  { name: "Euro/Kwacha Malauiana", code: "EUR-MWK" },
  { name: "Euro/Ringgit Malaio", code: "EUR-MYR" },
  { name: "Euro/Dólar Namíbio", code: "EUR-NAD" },
  { name: "Euro/Naira Nigeriana", code: "EUR-NGN" },
  { name: "Euro/Córdoba Nicaragueense", code: "EUR-NIO" },
  { name: "Euro/Rúpia Nepalesa", code: "EUR-NPR" },
  { name: "Euro/Rial Omanense", code: "EUR-OMR" },
  { name: "Euro/Balboa Panamenho", code: "EUR-PAB" },
  { name: "Euro/Sol do Peru", code: "EUR-PEN" },
  { name: "Euro/Kina Papua-Nova Guiné", code: "EUR-PGK" },
  { name: "Euro/Peso Filipino", code: "EUR-PHP" },
  { name: "Euro/Rúpia Paquistanesa", code: "EUR-PKR" },
  { name: "Euro/Guarani Paraguaio", code: "EUR-PYG" },
  { name: "Euro/Rial Catarense", code: "EUR-QAR" },
  { name: "Euro/Leu Romeno", code: "EUR-RON" },
  { name: "Euro/Dinar Sérvio", code: "EUR-RSD" },
  { name: "Euro/Franco Ruandês", code: "EUR-RWF" },
  { name: "Euro/Riyal Saudita", code: "EUR-SAR" },
  { name: "Euro/Rúpias de Seicheles", code: "EUR-SCR" },
  { name: "Euro/Libra Sudanesa", code: "EUR-SDG" },
  { name: "Euro/DSE", code: "EUR-SDR" },
  { name: "Euro/Shilling Somaliano", code: "EUR-SOS" },
  { name: "Euro/Dobra São Tomé/Príncipe", code: "EUR-STD" },
  { name: "Euro/Colon de El Salvador", code: "EUR-SVC" },
  { name: "Euro/Libra Síria", code: "EUR-SYP" },
  { name: "Euro/Lilangeni Suazilandês", code: "EUR-SZL" },
  { name: "Euro/Dinar Tunisiano", code: "EUR-TND" },
  { name: "Euro/Dólar de Trinidad", code: "EUR-TTD" },
  { name: "Euro/Dólar Taiuanês", code: "EUR-TWD" },
  { name: "Euro/Shilling Tanzaniano", code: "EUR-TZS" },
  { name: "Euro/Hryvinia Ucraniana", code: "EUR-UAH" },
  { name: "Euro/Shilling Ugandês", code: "EUR-UGX" },
  { name: "Euro/Peso Uruguaio", code: "EUR-UYU" },
  { name: "Euro/Som Uzbequistanês", code: "EUR-UZS" },
  { name: "Euro/Bolívar Venezuelano", code: "EUR-VEF" },
  { name: "Euro/Dong Vietnamita", code: "EUR-VND" },
  { name: "Euro/Franco CFA Central", code: "EUR-XAF" },
  { name: "Euro/Franco CFA Ocidental", code: "EUR-XOF" },
  { name: "Euro/Franco CFP", code: "EUR-XPF" },
  { name: "Euro/Kwacha Zambiana", code: "EUR-ZMK" },
  { name: "Cedi Ganês/Euro", code: "GHS-EUR" },
  { name: "Dólar Neozelandês/Euro", code: "NZD-EUR" },
  { name: "Dólar de Cingapura/Euro", code: "SGD-EUR" },
  { name: "Dirham dos Emirados/Euro", code: "AED-EUR" },
  { name: "Coroa Dinamarquesa/Euro", code: "DKK-EUR" },
  { name: "Euro/Dólar do Caribe Oriental", code: "EUR-XCD" },
  { name: "Dólar de Hong Kong/Euro", code: "HKD-EUR" },
  { name: "Peso Mexicano/Euro", code: "MXN-EUR" },
  { name: "Coroa Norueguesa/Euro", code: "NOK-EUR" },
  { name: "Zlóti Polonês/Euro", code: "PLN-EUR" },
  { name: "Rublo Russo/Euro", code: "RUB-EUR" },
  { name: "Riyal Saudita/Euro", code: "SAR-EUR" },
  { name: "Coroa Sueca/Euro", code: "SEK-EUR" },
  { name: "Nova Lira Turca/Euro", code: "TRY-EUR" },
  { name: "Dólar Taiuanês/Euro", code: "TWD-EUR" },
  { name: "Bolívar Venezuelano/Euro", code: "VEF-EUR" },
  { name: "Rand Sul-Africano/Euro", code: "ZAR-EUR" },
  { name: "Dirham Marroquino/Euro", code: "MAD-EUR" },
  { name: "Won Sul-Coreano/Euro", code: "KRW-EUR" },
  { name: "Libra Egípcia/Euro", code: "EGP-EUR" },
  { name: "Euro/Metical de Moçambique", code: "EUR-MZN" },
  { name: "Rúpia Indiana/Euro", code: "INR-EUR" },
  { name: "Dinar Jordaniano/Euro", code: "JOD-EUR" },
  { name: "Dinar Kuwaitiano/Euro", code: "KWD-EUR" },
  { name: "Euro/Manat Azeri", code: "EUR-AZN" },
  { name: "Euro/Dram Armênio", code: "EUR-AMD" },
  { name: "Euro/Somoni do Tajiquistão", code: "EUR-TJS" },
  { name: "Euro/Rublo Russo", code: "EUR-RUB" },
  { name: "Florim Húngaro/Euro", code: "HUF-EUR" },
  { name: "Lari Georgiano/Euro", code: "GEL-EUR" },
  { name: "Euro/Lari Georgiano", code: "EUR-GEL" },
  { name: "Rupia Indonésia/Euro", code: "IDR-EUR" },
  { name: "Euro/Kwanza Angolano", code: "EUR-AOA" },
  { name: "Rublo Bielorrusso/Euro", code: "BYN-EUR" },
  { name: "Prata/Euro", code: "XAGG-EUR" },
  { name: "Sol do Peru/Euro", code: "PEN-EUR" },
  { name: "Ouro/Dólar Americano", code: "XAU-USD" },
  { name: "Ouro/Euro", code: "XAU-EUR" },
  { name: "Dólar Americano/Real Brasileiro", code: "USD-BRLPTAX" },
  { name: "Dólar Neozelandês/Iene Japonês", code: "NZD-JPY" },
  { name: "Libra Esterlina/Iene Japonês", code: "GBP-JPY" },
  { name: "Libra Esterlina/Franco Suíço", code: "GBP-CHF" },
  { name: "Ouro/Real Brasileiro", code: "XAU-BRL" },
  { name: "Dólar Canadense/Iene Japonês", code: "CAD-JPY" },
  { name: "Peso Chileno/Euro", code: "CLP-EUR" },
  { name: "Peso Chileno/Boliviano", code: "CLP-BOB" },
  { name: "Prata Spot/Euro", code: "XAG-EUR" },
  { name: "Prata Spot/Dólar Americano", code: "XAG-USD" },
  { name: "Prata Spot/Real Brasileiro", code: "XAG-BRL" },
  { name: "Dinar Sérvio/Real Brasileiro", code: "RSD-BRL" },
  { name: "Real Brasileiro/Dinar Sérvio", code: "BRL-RSD" },
  { name: "Won Sul-Coreano/Real Brasileiro", code: "KRW-BRL" },
  { name: "Real Brasileiro/Prata Spot", code: "BRL-XAG" },
  { name: "Dólar Australiano/Iene Japonês", code: "AUD-JPY" },
  { name: "Dólar Australiano/Dólar Neozelandês", code: "AUD-NZD" },
  { name: "Brett/Dólar Americano", code: "BRETT-USD" },
  { name: "Brett/Real Brasileiro", code: "BRETT-BRL" },
  { name: "Brett/Euro", code: "BRETT-EUR" },
  { name: "Solana/Dólar Americano", code: "SOL-USD" },
  { name: "Solana/Real Brasileiro", code: "SOL-BRL" },
  { name: "Solana/Euro", code: "SOL-EUR" },
  { name: "Binance Coin/Dólar Americano", code: "BNB-USD" },
  { name: "Binance Coin/Real Brasileiro", code: "BNB-BRL" },
  { name: "Binance Coin/Euro", code: "BNB-EUR" },
  { name: "Franco Suíço/Iene Japonês", code: "CHF-JPY" },
  { name: "Libra Esterlina/Rand Sul-Africano", code: "GBP-ZAR" },
  { name: "Dólar Australiano/Franco Suíço", code: "AUD-CHF" },
  { name: "Libra Esterlina/Dólar Australiano", code: "GBP-AUD" },
  { name: "Peso Argentino/Peso Chileno", code: "ARS-CLP" },
  { name: "Peso Argentino/Sol do Peru", code: "ARS-PEN" },
  { name: "Dólar Canadense/Hryvinia Ucraniana", code: "CAD-UAH" },
  { name: "Euro/Real Brasileiro Turismo", code: "EUR-BRLT" },
  { name: "Euro/Real Brasileiro", code: "EUR-BRLPTAX" },
  { name: "Real Brasileiro/Ouro", code: "BRL-XAU" },
  { name: "Dólar do Caribe Oriental/Libra Esterlina", code: "XCD-GBP" },
  { name: "Libra Esterlina/Dólar do Caribe Oriental", code: "GBP-XCD" },
  { name: "Peso Mexicano/Dólar do Caribe Oriental", code: "MXN-XCD" },
  { name: "Dólar Neozelandês/Novo Shekel Israelense", code: "NZD-ILS" },
  { name: "Colón Costarriquenho/Dólar Americano", code: "CRC-USD" },
  { name: "Colón Costarriquenho/Real Brasileiro", code: "CRC-BRL" },
  { name: "Guarani Paraguaio/Peso Argentino", code: "PYG-ARS" },
  { name: "Leu Romeno/Real Brasileiro", code: "RON-BRL" },
  { name: "Real Brasileiro/Colón Costarriquenho", code: "BRL-CRC" },
  { name: "Novo Shekel Israelense/Dólar Neozelandês", code: "ILS-NZD" },
  { name: "Guarani Paraguaio/Euro", code: "PYG-EUR" },
  { name: "Dólar Americano/Dólar das Ilhas Cayman", code: "USD-KYD" },
  { name: "Dólar do Caribe Oriental/Dólar Americano", code: "XCD-USD" },
  { name: "Leu Romeno/Dólar Americano", code: "RON-USD" },
  { name: "Libra Egípcia/Real Brasileiro", code: "EGP-BRL" },
  { name: "Franco CFA Ocidental/Dólar Americano", code: "XOF-USD" },
  { name: "Shilling Queniano/Dólar Americano", code: "KES-USD" },
  { name: "Shilling Queniano/Real Brasileiro", code: "KES-BRL" },
  { name: "Peso Filipino/Real Brasileiro", code: "PHP-BRL" },
  { name: "Florim Húngaro/Real Brasileiro", code: "HUF-BRL" },
  { name: "Coroa Checa/Dólar Americano", code: "CZK-USD" },
  { name: "Coroa Checa/Real Brasileiro", code: "CZK-BRL" },
  { name: "Libra Sudanesa/Dólar Americano", code: "SDG-USD" },
  { name: "Franco CFP/Dólar Americano", code: "XPF-USD" },
  { name: "Franco CFP/Euro", code: "XPF-EUR" },
  { name: "Guilder das Antilhas/Dólar Americano", code: "ANG-USD" },
  { name: "Yuan Chinês/Iene Japonês", code: "CNY-JPY" },
  { name: "Peso Chileno/Peso Colombiano", code: "CLP-COP" },
  { name: "Peso Colombiano/Peso Chileno", code: "COP-CLP" },
  { name: "Libra Esterlina/Real Brasileiro", code: "GBP-BRLPTAX" },
  { name: "Iene Japonês/Real Brasileiro", code: "JPY-BRLPTAX" },
  { name: "Franco Suíço/Real Brasileiro", code: "CHF-BRLPTAX" },
  { name: "Dólar Canadense/Real Brasileiro", code: "CAD-BRLPTAX" },
  { name: "Dólar Australiano/Real Brasileiro", code: "AUD-BRLPTAX" },
  { name: "Coroa Dinamarquesa/Real Brasileiro", code: "DKK-BRLPTAX" },
  { name: "Coroa Sueca/Real Brasileiro", code: "SEK-BRLPTAX" },
  { name: "Coroa Norueguesa/Real Brasileiro", code: "NOK-BRLPTAX" },
  { name: "Coroa Norueguesa/Coroa Sueca", code: "NOK-SEK" },
  { name: "Coroa Sueca/Coroa Norueguesa", code: "SEK-NOK" },
] as const;
